### ISSUE TITLE
BadUSB scripts on iOS don't work

### ISSUE THREAD

**Issue by viac92** [FalsePhilosopher/badusb#16]
Hi @FalsePhilosopher first of all great work with this repo is really useful!

Secondly, do you have some suggestions to run badusb on iOS? 

I tried with the standard apple usbc-lightning cable on a iphone 13 mini with [this script](https://github.com/FalsePhilosopher/badusb/tree/main/prank/Unix-like/iOS/RickRoll_Apple), but it didn't work.

The flipper starts the script but it gets stuck at 44%, I think count the REM comment too, so it gets stuck at the first command.

Any ideas?

**Comment by FalsePhilosopher** [comment]
Checking that script it looks like the rickroll link did not have a STRING function in front of it so it would error on that line. I went back to the original script repo and pulled an updated version of that script that fixes that error. So that script should work now. If not it's because apple sucks ass and for some reason puts the usb host capabilities inside the ipad camera chip, don't ask me why that do that stupid shit. But you need an ipad camera chip to have usb host capabilities, so you need the lightning to usb 3 camera dongle that contains an ipad camera chip https://www.apple.com/shop/product/MK0W2AM/A/lightning-to-usb-3-camera-adapter
